"""Config generation — startup.sh, model.yaml, systemd unit."""

import os
from pathlib import Path


def generate_startup_script(target: Path, env_vars: dict, port: int = 8188,
                            vram_gb: int = 16) -> Path:
    """Generate a startup.sh script with correct ROCm environment."""
    target = Path(target).expanduser()
    script_path = target / "startup.sh"

    # ROCm performance tuning (inspired by Beinsezii/comfyui-amd-go-fast)
    perf_env = {
        "PYTORCH_HIP_ALLOC_CONF": "expandable_segments:True",
        "MIOPEN_FIND_MODE": "FAST",
    }
    all_env = {**env_vars, **perf_env}
    env_lines = "\n".join(f"export {k}={v}" for k, v in all_env.items())

    venv_python = target / ".venv" / "bin" / "python3"

    # ComfyUI flags based on VRAM
    if vram_gb >= 16:
        comfy_flags = "--bf16-vae --bf16-unet --bf16-text-enc"
    elif vram_gb >= 12:
        comfy_flags = "--bf16-vae --lowvram"
    else:
        comfy_flags = "--lowvram --bf16-vae"

    script = f"""#!/bin/bash
# Auto-generated by comfyui-rocm-setup
# Starts ComfyUI with correct ROCm environment for your AMD GPU
# Includes ROCm performance tuning (expandable_segments, MIOpen FAST)

# ROCm environment + performance tuning
{env_lines}

# Start ComfyUI
cd "{target}"
{venv_python} main.py --port {port} --listen 127.0.0.1 {comfy_flags}
"""
    script_path.write_text(script)
    script_path.chmod(0o755)
    return script_path


def generate_config(target: Path, gpu: dict, rocm_version: str) -> Path:
    """Generate a ComfyUI config file with GPU-specific settings."""
    target = Path(target).expanduser()
    config_path = target / "config.yaml"  # ComfyUI's extra_model_paths.yaml

    vram_gb = gpu.get("vram_gb", 8)

    # Recommended settings based on VRAM
    if vram_gb >= 16:
        vram_settings = {
            "vae_bits": "bf16",
            "attention_mode": "sdpa",
            "cache_classics": True,
            "lowvram": False,
        }
    elif vram_gb >= 12:
        vram_settings = {
            "vae_bits": "fp16",
            "attention_mode": "sdpa",
            "cache_classics": True,
            "lowvram": False,
        }
    else:
        vram_settings = {
            "vae_bits": "fp16",
            "attention_mode": "xformers",
            "cache_classics": False,
            "lowvram": True,
        }

    config = f"""# Auto-generated by comfyui-rocm-setup
# GPU: {gpu.get('name', 'Unknown')} ({gpu.get('arch', 'unknown')})
# VRAM: {vram_gb} GB
# ROCm: {rocm_version}

# Extra model paths (add your own)
# extra_model_paths:
#   my_models:
#     base_path: ~/models
#     checkpoints: checkpoints/
#     loras: loras/

# Performance settings (auto-tuned for {vram_gb}GB VRAM)
# VAE: {vram_settings['vae_bits']}
# Attention: {vram_settings['attention_mode']}
# Low VRAM mode: {vram_settings['lowvram']}
"""
    config_path.write_text(config)
    return config_path


def generate_systemd_unit(target: Path, env_vars: dict, user: str = None,
                           port: int = 8188) -> Path:
    """Generate a systemd user unit for ComfyUI."""
    target = Path(target).expanduser()
    unit_path = Path.home() / ".config" / "systemd" / "user" / "comfyui.service"
    unit_path.parent.mkdir(parents=True, exist_ok=True)

    venv_python = target / ".venv" / "bin" / "python3"
    env_section = "\n".join(f"Environment={k}={v}" for k, v in env_vars.items())

    unit = f"""[Unit]
Description=ComfyUI with ROCm (AMD GPU)
After=network.target

[Service]
Type=simple
WorkingDirectory={target}
ExecStart={venv_python} main.py --port {port} --listen 127.0.0.1
{env_section}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
"""
    unit_path.write_text(unit)
    return unit_path